### ISSUE TITLE
ParameterCollection template has a possible null reference pointers for Key and Text properties

### ISSUE THREAD

**Issue by edurdias** [edurdias/RunningObjects#14]
Review the EditorTemplate and DisplayTemplate ParameterCollection for possible null reference exceptions. Issue identified at #12.

**Comment by ghost** [comment]
Hi Eduardo,

Any progress on this problem?

**Comment by edurdias** [comment]
Hi @georgih,

Please take a look on changed files [here](https://github.com/edurdias/RunningObjects/commit/01a4056b4a49f7e8c4f6b9e60722a2d30648ad15). They will also be available in the next release.

Thanks,
Eduardo

**Comment by ghost** [comment]
Hi Eduardo,

This works nice!

Sorry to say that again, but I encountered another issue, this time with nullable DateTime types, I think.

“The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value. The statement has been terminated.”

I have no time at the moment do dig for the cause of the problem, but you can reconstruct the error using my project http://sdrv.ms/T9YAfe
Just add Category, Author, Book and Borrower. Then try to create a Borrowing using “01/xx/2012” as dates.
Error appears on saving the borrowing.
I suspect something is going on between SQL and EF DataTime types but not 100% sure.

Cheers,
Georgi

**Comment by edurdias** [comment]
Hi @georgih,

Please check if your Date property is non-nullable and if you trying to save nullable. 

Reference: http://goo.gl/50Vxr

**Comment by ghost** [comment]
Hi Eduardo,

The ReturnedOn field inside the Borrowing model is nullable DateTime.
The project itself is not doing anything. I’ve started from an MVC 3 app with RO template and just added the models and configuration.
Rest is all handled by RunningObjects, thus I would expect the situation to be handled inside RO.

Sorry to put a hard time on you but I just want to help ☺
I really seriously like the RO idea. It will help a lot of people to quickly build a lot of projects.

You should think on putting in Business Intelligence, Data Analysis and Reporting capabilities.

Cheers,
Georgi
