### ISSUE TITLE
Write SOME documentation.

### ISSUE THREAD

**Issue by svallory** [edurdias/RunningObjects#7]
RunningObjects already has a lot of features. At this point, IMHO, the most valuable addition to the project would be some documentation. Even simple lists of features with a breaf explanation would be great. E.g.:
- Which class and property attributes does RunningObject have and what they do?
- How can I hand pick the classes I wan't to scaffold?
- How do I add new "actions" to the app?
- How do Repositories, and it's methods, behave?
- How do model methods affect the generated app?

An so on... I'm really eager to use RO, but it's really hard to get started. Again, IMHO, you should stop all the development you are doing and write about what RO already have. I think enabling the repo wiki would be a good idea. Without documentation it's really hard to get help from the community.

Please, don't take me the wrong way, I know how hard it is to tackle a project this big by yourself (I've been there). I believe RO will be great, if it gathers help from the community (I'm planning on helping too!), and documentation plays a big role on this.

Cheers!

**Comment by edurdias** [comment]
Hi Saulo,

I totally agree with you and I am currently working in the documentation and two samples, one quite simple for the getting started and another one more complex and with more tricks.

I will release these documents and also the new website (built with RO) this week (hopefully before Friday).

The idea is initially to cover the following topics (please let me know what you think):
- Getting Started - Explaining the main benefits, how it works and what to do to get started.
- ASP.NET MVC  - The correlation with an ASP.NET MVC application and what RO changes.
- Basic Concepts - How we use Object Orientation to help us to build a RO application.
- ... (under development)

Suggestions will be very well accepted. =)

Thanks!

**Comment by svallory** [comment]
I think those topics are great! And they must be part of the docs, but I believe the info you have on the current site is enough for now. What I mean is I'm already sold! I get what RO does, and don't really care how he does it internally. At least not as much as to "what can I do with it".

What I miss here is mostly a list of all "do this to get that". Simple example: I haven't see the `NotScaffold` (which i think should be called `DontScaffold`) attribute documented anywhere. Not even the class has docs if I recall. A Simple XmlDoc in the class would help in this case.

So, I would update the first topic, since the current Get Started is outdated, then link to the wiki and throw there as many "quick" info as I could. Framework documentation is hard to write. I once wrote a proposal (in portuguese) for a documentation platform for frameworks which I never implemented, but the research on framework documentation may be useful to you: 

http://www.saulovallory.com/download/article/SoftDoc-draft-pt.pdf

**Comment by edurdias** [comment]
Hi Saulo,

I have started to work in the documentation and it is now available online.
I still working on it and in the next days it will have more details regarding tricks and advanced features.

Thanks,
Eduardo

**Comment by svallory** [comment]
Very glad to know that!
